main: de.kaleidox.e2uClaim.E2UClaim
name: ${rootProject.name}
version: $pluginVersion
author: $userbase
description: $projectDescription
api-version: $mcVersionMj
depend:
  - Spiroid

commands:
  e2uClaim:
    aliases:
      - e2uc
    description: e2uClaim configuration command
    permission: e2uclaim.admin
    permission-message: "§7[§ae2uClaim§7] §cYou are missing the permission: §be2uclaim.admin§c!"
  lock:
    description: Locks a block
    permission: e2uclaim.lock
    permission-message: "§7[§ae2uClaim§7] §cYou are missing the permission: §be2uclaim.lock§c!"
  unlock:
    description: Unlocks a block
    permission: e2uclaim.lock
    permission-message: "§7[§ae2uClaim§7] §cYou are missing the permission: §be2uclaim.lock§c!"
  claim:
    description: Claim an area for yourself
    permission: e2uclaim.claim
    permission-message: "§7[§ae2uClaim§7] §cYou are missing the permission: §be2uclaim.claim§c!"
  unclaim:
    description: Unclaim an area you have claimed before
    permission: e2uclaim.claim
    permission-message: "§7[§ae2uClaim§7] §cYou are missing the permission: §be2uclaim.claim§c!"