main: de.kaleidox.e2uClaim.E2UClaim
name: e2uClaim
version: 0.2.0
author: Kaleidox
description: easy-to-use claiming plugin
api-version: "1.13"
commands:
  e2uClaim:
    aliases:
      - e2uc
    description: e2uClaim configuration command
    permission: e2uclaim.admin
    permission-message: "§7[§ae2uClaim§7] §cYou are missing permission!"
  lock:
    description: Locks a block
    permission: e2uclaim.lock
    permission-message: "§7[§ae2uClaim§7] §cYou are missing permission!"
  unlock:
    description: Unlocks a block
    permission: e2uclaim.lock
    permission-message: "§7[§ae2uClaim§7] §cYou are missing permission!"
  claim:
    description: Claim an area for yourself
    permission: e2uclaim.claim
    permission-message: "§7[§ae2uClaim§7] §cYou are missing permission!"
  unclaim:
    description: Unclaim an area you have claimed before
    permission: e2uclaim.claim
    permission-message: "§7[§ae2uClaim§7] §cYou are missing permission!"